   sonar.projectKey=Virajjj11_7.1C-DevSecOps
   sonar.organization=virajjj11
   sonar.host.url=https://sonarcloud.io

   sonar.sources=.
   sonar.exclusions=node_modules/**,test/**
   sonar.javascript.lcov.reportPaths=coverage/lcov.info

   sonar.projectName=NodeJS Goof Vulnerable App
   sonar.sourceEncoding=UTF-8
